# SHM and Grid Configuration
MAX_TARGETS = 64
MAX_SEED_SIZE = 1024000
MAP_SIZE = 1048576 
MAX_PATH_LEN = 512
GRID_DIM = 1024
COARSEN_FACTOR = 4
GRID_DIM_COARSE = GRID_DIM // COARSEN_FACTOR

# File Paths
CFG_EDGES_FILE = "cfg_edges.txt"
BB_LINES_MAP_FILE = "bb_lines_map.txt"
TARGET_BB_MAP_FILE = "target_bb_map.txt"

# Process/SHM Names
TARGET_PROCESS_NAME = "target_normal"
DIST_KV_SHM_NAME = "AFL_DIST_KV_SHM_ID"
COVERAGE_MAP_SHM_NAME = "AFL_SHM_ID"

# Dash Settings
DEFAULT_REFRESH_INTERVAL = 1000
MIN_REFRESH_INTERVAL = 500
DEFAULT_TOP_N = 0
DEFAULT_CFG_ENABLED = False
DEFAULT_LLM_THRESHOLD = 300
MIN_LLM_THRESHOLD = 10
DEFAULT_LLM_ENDPOINT = "http://10.0.0.9:11434"
DEFAULT_LLM_MODEL = "llama3.1:8b"
