import os

# SHM and Grid Configuration
MAX_TARGETS = 64
MAX_SEED_SIZE = 512
MAP_SIZE = 1048576 
GRID_DIM = 1024
COARSEN_FACTOR = 4
GRID_DIM_COARSE = GRID_DIM // COARSEN_FACTOR

# File Paths
CFG_EDGES_FILE = "cfg_edges.txt"

# Process/SHM Names
TARGET_PROCESS_NAME = "target_normal"
DIST_KV_SHM_NAME = "AFL_DIST_KV_SHM_ID"
COVERAGE_MAP_SHM_NAME = "AFL_SHM_ID"

# Dash Settings
DEFAULT_REFRESH_INTERVAL = 10000
MIN_REFRESH_INTERVAL = 5000
